### ISSUE TITLE
Unknown option -s

### ISSUE THREAD

**Issue by mahmoodn** [knightcrawler25/Optix-PathTracer#10]
How can I give input to the program? I have downloaded a blend file (scene?) and here is the command I use
```
$ ./optixPathTracer -s ../../samples/grey.white.room.03.bs.blend
Unknown option '-s'

Usage: ./optixPathTracer [options]
App Options:
  -h | --help                  Print this usage message and exit.
  -f | --file <output_file>    Save image to file and exit.
  -n | --nopbo                 Disable GL interop for display buffer.
  -s | --scene                 Provide a scene file for rendering.
App Keystrokes:
  q  Quit
  s  Save image to 'optixPathTracer.png'
  f  Re-center camera

```

**Comment by knightcrawler25** [comment]
I fixed the scene input now. Earlier it was working only with -scene but now it should work with -s or -scene. Also, the scene files are not .blend files. You can find some of them in the src/data directory. 
For example, the scene file to render the cornell box is the src/data/cornell.scene and the corresponding obj files are in the src/data/cornell_box folder. There are also some additional files in src/data/data.rar to play around with
