### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by apchenstu** [knightcrawler25/Optix-PathTracer#5]
Hi, it is a very nice project!! 
I want to add some animation to the objects,  I tried to add transform node to the GeometryGroup, similar as Optix sample "optixDynamicGeometry", the object did move, but it seems the shading and reflection are not correct, do you know why? Thanks!
![00000](https://user-images.githubusercontent.com/16453770/49400206-631d7f80-f6f8-11e8-9d2b-feccb61a376b.png)

![00001](https://user-images.githubusercontent.com/16453770/49400230-703a6e80-f6f8-11e8-8139-2159d5094d90.png)
![00002](https://user-images.githubusercontent.com/16453770/49400236-76304f80-f6f8-11e8-909f-c89c5dd56ed7.png)

**Comment by knightcrawler25** [comment]
I'll have a look and get back to you. From the screenshots it looks like not all meshes have rotated around the axis of rotation, like the red console for example. Could you share what changes you've made so that it's easier for me to check. :)

**Comment by knightcrawler25** [comment]
Closing since this issue was solved here:
https://devtalk.nvidia.com/default/topic/1044859/optix/optix-render-animation/
