### ISSUE TITLE
RT_CALLABLE_PROGRAM??

### ISSUE THREAD

**Issue by tom-sakai601220** [knightcrawler25/Optix-PathTracer#9]
I run sample I was caught exception as follows.
OptiX Error: 'Invalid context (Details: Function "_rtProgramGetId" caught exception: Validation error: _Z6SampleR17MaterialParameterR5StateR19PerRayData_radiance function with semantic type BINDLESS_CALLABLE_PROGRAM accesses the rtCurrentRay semantic variable.)'

What's up??

I Develop under Optix 6.0,0.

**Comment by knightcrawler25** [comment]
I think it has to do with me using a variable from PerRayData_radiance in the callable program. The code runs fine on Optix 5.x but I guess the newer versions of Optix have enforced some restrictions. Is this error in disney.cu?

**Comment by knightcrawler25** [comment]
I have fixed the code. Can you try now and see if its working for you?

**Comment by tom-sakai601220** [comment]
Thank you for changing the code.
